name: bicapture
description: Capture Microsoft Power BI Dashboard as image.
version: 1.0.0
homepage: https://github.com/yuzumone/bicapture

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  puppeteer: ^1.22.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  bicapture:
